`timescale 1ns/1ps

// Group 2 implementation of the standard Didactic student-subsystem leaf.
// Clock gating, address-window selection, and final IRQ masking belong to the
// surrounding student_wrapper generated by the SoC integration flow.
module subsystem #(
    parameter                              NUM_GPIO = 16,
    parameter                              APB_AW   = 16,
    parameter                              APB_DW   = 32
) (
    input                [APB_AW-1:0]   PADDR,
    input                               PENABLE,
    input                               PSEL,
    input                [APB_DW-1:0]   PWDATA,
    input                               PWRITE,
    output               [APB_DW-1:0]   PRDATA,
    output                              PREADY,
    output                              PSLVERR,

    input                               clk,

    output logic                        irq,

    input                [NUM_GPIO-1:0] pmod_gpi,
    output               [NUM_GPIO-1:0] pmod_gpio_oe,
    output               [NUM_GPIO-1:0] pmod_gpo,

    input                               irq_en,
    input                               reset_n
);

  group2_topmodule i_group2_topmodule (
    .PADDR           (PADDR[15:0]),
    .PENABLE         (PENABLE),
    .PSEL            (PSEL),
    .PWDATA          (PWDATA[31:0]),
    .PWRITE          (PWRITE),
    .PRDATA          (PRDATA[31:0]),
    .PREADY          (PREADY),
    .PSLVERR         (PSLVERR),
    .clk_i           (clk),
    .rst_ni          (reset_n),
    .wrapper_fault_i (1'b0),
    .irq_en_i        (irq_en),
    .pmod_gpi        (pmod_gpi[15:0]),
    .irq_o           (irq),
    .pmod_gpo        (pmod_gpo[15:0]),
    .pmod_gpio_oe    (pmod_gpio_oe[15:0])
  );

endmodule
