`timescale 1ns/1ps

//-----------------------------------------------------------------------------
// Compact firmware-visible register bank for the SA subsystem.
//
// RegBank stores the current CONFIG word, converts CONTROL writes into
// one-cycle command pulses, and exposes only the control/status fields needed
// by the first integrated SA subsystem.  It does not own sequencing; all
// long-lived transaction state is generated by group2_sa_ctrl.
//-----------------------------------------------------------------------------

module group2_regbank (
    input  logic        clk_i,
    input  logic        rst_ni,

    input  logic [15:0] local_addr_i,
    input  logic [31:0] bus_wdata_i,
    input  logic        reg_wena_i,
    input  logic        reg_rena_i,

    input  logic [2:0]  phase_i,
    input  logic        weights_valid_i,
    input  logic        done_sticky_i,
    input  logic        error_sticky_i,
    input  logic        overflow_sticky_i,
    input  logic        output_valid_i,
    input  logic        output_full_i,
    input  logic        output_blocked_i,
    input  logic [31:0] output_words_i,
    input  logic [31:0] error_code_i,

    input  logic        irq_en_i,
    input  logic [15:0] pmod_gpi,

    output logic [31:0] config_o,
    output logic        config_valid_o,
    output logic        load_weights_cmd_o,
    output logic        release_output_cmd_o,
    output logic        clear_done_cmd_o,
    output logic        clear_error_cmd_o,
    output logic        soft_reset_cmd_o,
    output logic [31:0] reg_rdata_o,
    output logic        irq_o,
    output logic [15:0] pmod_gpo,
    output logic [15:0] pmod_gpio_oe
);

  import group2_pkg::*;

  logic [31:0] config_q;
  logic [31:0] status_word;
  logic        control_write;

  // CONTROL is command-only. Bits are not stored; each accepted write creates
  // pulses consumed by the FSM/output control path.
  assign control_write        = reg_wena_i && (local_addr_i == OFF_CONTROL);
  assign load_weights_cmd_o   = control_write && bus_wdata_i[0];
  assign release_output_cmd_o = control_write && bus_wdata_i[1];
  assign clear_done_cmd_o     = control_write && bus_wdata_i[2];
  assign clear_error_cmd_o    = control_write && bus_wdata_i[3];
  assign soft_reset_cmd_o     = control_write && bus_wdata_i[4];

  assign config_o       = config_q;
  assign config_valid_o = config_valid(config_q);

  // STATUS is intentionally compact. Progress counters and debug-only fields
  // are not stored in hardware at this stage.
  //
  // Error hierarchy visible to firmware:
  //   - error_sticky + ERROR_CODE reports rejected APB accesses or fatal
  //     controller faults.
  //   - phase == PH_ERROR means the controller dropped the current context and
  //     firmware should clear/reset before starting a new transaction.
  //   - overflow_sticky is independent from ERROR_CODE; saturated MAC results
  //     are still returned through the output buffer.
  assign status_word = {
    8'd0,
    output_valid_i ? output_words_i[7:0] : 8'd0, // bits 23:16
    1'd0,                                        // bit 15 reserved
    overflow_sticky_i,                           // bit 14
    error_code_i[3:0],                           // bits 13:10
    phase_i,                                     // bits 9:7
    output_blocked_i,                            // bit 6
    output_full_i,                               // bit 5
    output_valid_i,                              // bit 4
    weights_valid_i,                             // bit 3
    done_sticky_i,                               // bit 2
    error_sticky_i,                              // bit 1
    ((phase_i == PH_LOAD_WEIGHTS) ||
     (phase_i == PH_BATCH_COMPUTE) ||
     (phase_i == PH_DRAIN_WRITEBACK))            // bit 0
  };

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      config_q <= 32'd0;
    end else begin
      // Soft reset clears the run configuration together with FSM state.
      if (soft_reset_cmd_o) begin
        config_q <= 32'd0;
      end else if (reg_wena_i && (local_addr_i == OFF_CONFIG)) begin
        config_q <= bus_wdata_i;
      end
    end
  end

  always_comb begin
    // Combinational readback keeps APB reads single-cycle in this first pass.
    unique case (local_addr_i)
      OFF_CONTROL:      reg_rdata_o = 32'd0;
      OFF_STATUS:       reg_rdata_o = status_word;
      OFF_CONFIG:       reg_rdata_o = config_q;
      // OFF_PROGRESS is reserved for a future debug build.  Keeping it readable
      // as zero avoids forcing firmware to special-case the compact version.
      OFF_PROGRESS:     reg_rdata_o = 32'd0;
      OFF_ERROR_CODE:   reg_rdata_o = error_code_i;
      OFF_OUTPUT_WORDS: reg_rdata_o = output_valid_i ? output_words_i : 32'd0;
      default:          reg_rdata_o = 32'd0;
    endcase
  end

  // Compact v1 uses SoC-level irq_en_i directly; local IRQ mask registers are
  // deferred until the debug/control map grows.
  assign irq_o = irq_en_i && (done_sticky_i || error_sticky_i);

  // Debug sideband is intentionally inactive in this compact control-plane
  // skeleton. Keep the ports tied off so the SoC wrapper contract stays stable.
  assign pmod_gpo     = 16'd0;
  assign pmod_gpio_oe = 16'd0;

  wire _unused_regbank = &{1'b0, reg_rena_i, pmod_gpi, 1'b0};

endmodule
